global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "decks_service"
    static_configs:
      - targets: ["host.docker.internal:8001"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "teaching_service"
    static_configs:
      - targets: ["host.docker.internal:8002"]
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: "minio_storage"
    static_configs:
      - targets: ["host.docker.internal:9000"]
    scrape_interval: 5s
    metrics_path: /minio/v2/metrics/cluster

  - job_name: "auth_service"
    static_configs:
      - targets: ["host.docker.internal:8005"]
    scrape_interval: 5s
    metrics_path: /metrics
